### ISSUE TITLE
The process 'git' failed with exit code 128

### ISSUE THREAD

**Issue by Chrizz604** [remorses/bump-version#11]
Hey there, I need some help to setup this github action because currently it does crash for some reason. I'm not sure why it does error with `not in a git directory` because it is in a `github` folder and the package.json file does also exist.

> package.json
```json
{
  "name": "bumpversiontest",
  "version": "[bump]",
  "description": "",
  "keywords": [],
  "author": "Chrizz",
  "license": "MIT"
}
```
> .github/workflows/main.yml
```yml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Bump versions
      uses: remorses/bump-version@js
      with:
          version_file: package.json
          github_token: ${{ secrets.APP_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
![image](https://user-images.githubusercontent.com/80067615/123473841-6bf93800-d5f9-11eb-82cf-a5e518bb0b4d.png)
