### ISSUE TITLE
Error on version tag creation

### ISSUE THREAD

**Issue by jannotti-glaucio** [remorses/bump-version#22]
Hi Guys !
I'm trying to use the bump-version action but it's not working!

The error is occurring when it tries to create the version tag:
```
creating tag "image_0.0.1"
/home/runner/work/_actions/remorses/bump-version/js/node_modules/@octokit/request/dist-node/index.js:66
        const error = new requestError.RequestError(message, status, {
                      ^
RequestError [HttpError]: Not Found
    at /home/runner/work/_actions/remorses/bump-version/js/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 05 Jul 2023 17:30:43 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=315[36](https://github.com/truzzt/FederatedCatalog/actions/runs/5467230118/jobs/9953254197#step:3:37)000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-api-version-selected': '2022-11-28',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '2FC2:[37](https://github.com/truzzt/FederatedCatalog/actions/runs/5467230118/jobs/9953254197#step:3:38)6A:2D0[39](https://github.com/truzzt/FederatedCatalog/actions/runs/5467230118/jobs/9953254197#step:3:40)7:5B6993:64A5A8C3',
    'x-ratelimit-limit': '1000',
    'x-ratelimit-remaining': '969',
    'x-ratelimit-reset': '1688580720',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '31',
    'x-xss-protection': '0'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/jannotti-glaucio/FederatedCatalog/tags?per_page=100',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit.js/16.30.0 Node.js/16.16.0 (Linux 5.15; x[64](https://github.com/truzzt/FederatedCatalog/actions/runs/5467230118/jobs/9953254197#step:3:65))',
      authorization: 'token [REDACTED]'
    },
    request: {
      hook: [Function: bound bound register],
      validate: {
        owner: { required: true, type: 'string' },
        page: { type: 'integer' },
        per_page: { type: 'integer' },
        repo: { required: true, type: 'string' }
      }
    }
  },
  documentation_url: 'https://docs.github.com/rest/reference/repos#list-repository-tags'
}
```

The .yml file is defined as below:
```
name: Build Image
on:
  push:
    branches:
      - 'develop'
jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Bump Version
        uses: remorses/bump-version@js
        with:
          version_file: ./launchers/VERSION
          prefix: image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Can anyone help me with this?
Regards
