### ISSUE TITLE
GITHUB_TOKEN Env Variable Needs to Be Set If Using with: github_token

### ISSUE THREAD

**Issue by chriswsh** [remorses/bump-version#7]
**Non-working yml**

```
- name: Bump version
        uses: remorses/bump-version@js
        with:
          version_file: ./.version
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Working yml**

```
- name: Bump version
        uses: remorses/bump-version@js
        with:
          version_file: ./.version
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Expected**

`github_token` only needs to be set once. I think I might have been running afoul of the check at https://github.com/remorses/bump-version/blob/js/src/commit.ts#L17, which only checks for the presence of the env variable.
