### ISSUE TITLE
Skip everything but the version_file

### ISSUE THREAD

**Issue by tkav** [remorses/bump-version#9]
I've listed multiple folders as `ignore` however it still took 8 minutes to update the `version_file`.

Is there a way to ignore everything but the `version_file` or bump the version without scanning the rest of the repository?

```yml
name: Bump version        
uses: remorses/bump-version@js        
with:            
     version_file: ./VERSION            
     github_token: ${{ secrets.GITHUB_TOKEN }}           
     ignore: build, css, dist, images, img, include, pdf
env:          
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}<!--EndFragment-->
```

I saw issue #1 but it looks like `skip_patterns` is no longer an option.
```
Unexpected input(s) 'skip_patterns', valid inputs are ['version_file', 'prefix', 'github_token', 'prerelease_tag', 'branch', 'ignore']
```

**Comment by tkav** [comment]
I've added an explicit parameter and it's working for me. The action is now running in around 15 seconds.
```yml
- name: Bump version
        uses: tkav/bump-version@explicit-option
        with:
            version_file: ./VERSION
            github_token: ${{ secrets.GITHUB_TOKEN }}
            explicit: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Added pull request #10
